# Generated by Django 3.0.3 on 2020-04-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_auto_20200414_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='alias',
        ),
        migrations.AlterField(
            model_name='covid',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='covid',
            name='reportedCases',
            field=models.CharField(max_length=40),
        ),
    ]
